[2019-03-31 01:55:28 +0000] [5151] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-03-31 09:43:02 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28167)
[2019-03-31 09:43:03 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28168)
[2019-03-31 09:43:03 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28169)
[2019-03-31 09:43:03 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28170)
[2019-03-31 09:43:03 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28174)
[2019-03-31 09:43:03 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28176)
[2019-03-31 09:43:03 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28178)
[2019-03-31 09:43:03 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28180)
[2019-03-31 09:43:03 +0000] [28163] [CRITICAL] WORKER TIMEOUT (pid:28181)
[2019-03-31 10:06:29 +0000] [28632] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-03-31 12:10:02 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:30624)
[2019-03-31 12:10:04 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:30614)
[2019-03-31 12:10:04 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:30616)
[2019-03-31 12:10:04 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:30617)
[2019-03-31 12:10:04 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:30618)
[2019-03-31 12:10:04 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:30620)
[2019-03-31 12:10:04 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:30623)
[2019-03-31 12:10:37 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:31751)
[2019-03-31 12:10:37 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:31752)
[2019-03-31 12:10:37 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:31753)
[2019-03-31 12:10:37 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:31754)
[2019-03-31 12:10:38 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:31755)
[2019-03-31 12:10:38 +0000] [30610] [CRITICAL] WORKER TIMEOUT (pid:31756)
[2019-03-31 14:07:25 +0000] [3749] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-03-31 22:17:57 +0000] [3839] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-03-31 22:17:57 +0000] [3837] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-01 01:20:39 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3840)
[2019-04-01 01:20:41 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3825)
[2019-04-01 01:20:41 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3826)
[2019-04-01 01:20:41 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3827)
[2019-04-01 01:20:41 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3829)
[2019-04-01 01:20:41 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3833)
[2019-04-01 01:20:41 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3836)
[2019-04-01 01:20:41 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3837)
[2019-04-01 01:20:41 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:3839)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9420)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9421)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9422)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9423)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9424)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9425)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9426)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9427)
[2019-04-01 03:35:17 +0000] [3820] [CRITICAL] WORKER TIMEOUT (pid:9428)
[2019-04-01 12:10:44 +0000] [18603] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-01 12:11:19,977] ERROR in app: Exception on /sync [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/psiturk/experiment.py", line 731, in regularpage
    return render_template(pagename)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: sync
[2019-04-01 15:43:01 +0000] [25084] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-02 04:00:42 +0000] [6790] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-04 03:58:23 +0000] [14229] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-05 14:20:50 +0000] [11169] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-05 14:20:51 +0000] [11171] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-05 19:22:30 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3568)
[2019-04-05 19:22:31 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3569)
[2019-04-05 19:22:31 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3573)
[2019-04-05 19:22:31 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3574)
[2019-04-05 19:22:31 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3576)
[2019-04-05 19:22:31 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3578)
[2019-04-05 19:22:31 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3579)
[2019-04-05 19:22:31 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3581)
[2019-04-05 19:22:31 +0000] [3564] [CRITICAL] WORKER TIMEOUT (pid:3582)
[2019-04-06 12:24:01 +0000] [5050] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5351)
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5353)
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5355)
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5357)
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5358)
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5360)
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5361)
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5363)
[2019-04-06 18:07:22 +0000] [5347] [CRITICAL] WORKER TIMEOUT (pid:5364)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16457)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16458)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16461)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16462)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16465)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16466)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16469)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16470)
[2019-04-07 12:10:06 +0000] [16453] [CRITICAL] WORKER TIMEOUT (pid:16474)
[2019-04-07 13:51:53 +0000] [9041] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12744)
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12746)
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12748)
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12750)
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12752)
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12754)
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12755)
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12758)
[2019-04-07 17:26:41 +0000] [12740] [CRITICAL] WORKER TIMEOUT (pid:12759)
[2019-04-07 22:56:32 +0000] [19036] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4321)
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4326)
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4327)
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4329)
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4330)
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4314)
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4315)
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4316)
[2019-04-08 21:27:59 +0000] [4309] [CRITICAL] WORKER TIMEOUT (pid:4317)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3220)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3221)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3222)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3223)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3224)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3225)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3226)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3227)
[2019-04-09 01:11:48 +0000] [3211] [CRITICAL] WORKER TIMEOUT (pid:3228)
[2019-04-10 13:44:53 +0000] [10688] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 397, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 387, in sendfile
    sent += sendfile(sockno, fileno, offset + sent, count)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/_sendfile.py", line 67, in sendfile
    raise OSError(e, os.strerror(e))
OSError: [Errno 32] Broken pipe
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10688)
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10689)
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10695)
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10697)
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10700)
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10701)
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10685)
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10686)
[2019-04-10 13:59:13 +0000] [10681] [CRITICAL] WORKER TIMEOUT (pid:10687)
